### ISSUE TITLE
GCC Cross-Compiler

### ISSUE THREAD

**Issue by kushagra765** [PQCraft/PhosphorOS#2]
You are using GCC to compile the OS. But you need a cross-compiler to compile the OS.

Also, you are passing `-fno-stack-protector` which breaks your kernel because you are not using a cross-compiler.

 [GCC Cross Compiler](https://wiki.osdev.org/GCC_Cross-Compiler)

[Why do I need a cross compiler](https://wiki.osdev.org/Why_do_I_need_a_Cross_Compiler)

**Comment by PQCraft** [comment]
Ok, well I have replaced the function that was causing the `undefined reference to `__stack_chk_fail_local'` with a return so it compiles now, but it just doesn't boot. It resets after I select any of the boot options. I do not care about this project anymore as this is really stupid and shouldn't be happening and i'm not going to debug it and find out what is wrong as I could care less. BTW, this anger is not aimed towards you, but is aimed at the obfuscated mess of code I have created. I will be deleting this repo in 3 days.

**Comment by PQCraft** [comment]
Ok, well I have replaced the function that was causing the `undefined reference to '__stack_chk_fail_local'` with a return so it compiles now, but it just doesn't boot. It resets after I select any of the boot options. I do not care about this project anymore as this is really stupid and shouldn't be happening and i'm not going to debug it and find out what is wrong as I couldn't care less. BTW, this anger is not aimed towards you, but is aimed at the obfuscated mess of code I have created. I will be deleting this repo in 3 days.

**Comment by kushagra765** [comment]
> Ok, well I have replaced the function that was causing the `undefined reference to '__stack_chk_fail_local'` with a return so it compiles now, but it just doesn't boot. It resets after I select any of the boot options. I do not care about this project anymore as this is really stupid and shouldn't be happening and i'm not going to debug it and find out what is wrong as I couldn't care less. BTW, this anger is not aimed towards you, but is aimed at the obfuscated mess of code I have created. I will be deleting this repo in 3 days.

Ok
